"""empty message

Revision ID: 9f1a44f83562
Revises: 53a078d140ee
Create Date: 2025-02-22 00:02:29.623293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f1a44f83562'
down_revision: Union[str, None] = '53a078d140ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_users', sa.Column('user_status_in_group', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_users', 'user_status_in_group')
    # ### end Alembic commands ###
